version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: partners-tech-interview-db
      MONGO_INITDB_ROOT_USERNAME: partnersTechInterviewUser
      MONGO_INITDB_ROOT_PASSWORD: partnersTechInterviewPassword
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  rabbit:
    image: rabbitmq:management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  clamav:
    image: mkodockx/docker-clamav:latest
    restart: unless-stopped
    ports:
      - "3310:3310"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 3310 || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  mongo_data: