version: "3"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: partners-tech-interview-db
      POSTGRES_USER: partnersTechInterviewUser
      POSTGRES_PASSWORD: partnersTechInterviewPassword
    ports:
      - '5432:5432'
  rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest