spring:
  application:
    name: partners-tech-interview
  data:
    mongodb:
      host: localhost
      database: partners-tech-interview-db
      username: partnersTechInterviewUser
      password: partnersTechInterviewPassword
      port: 27017
      authentication-database: admin
  rabbitmq:
    host: ${tech-interview.rabbitmq.host}
    port: ${tech-interview.rabbitmq.port}
    username: ${tech-interview.rabbitmq.username}
    password: ${tech-interview.rabbitmq.password}

clamav:
  host: clamav
  port: 3310